#!/bin/bash
chmod 600 terraform-key-pair.pem
eval "$(ssh-agent -s)"
ssh-add terraform-key-pair.pem
# ssh into bastion (use admin for debian) this is the key.pem
# generated by terraform inside environments/development or
# environments/production
ssh -i terraform-key-pair.pem -A -o StrictHostKeyChecking=no ubuntu@IP
# when you are inside bastion host, ssh into control planes and
# worker nodes (use admin for debian)
# ssh ubuntu@IP